# Generated by Django 4.2.30 on 2026-08-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandle', '0004_alter_booked_options_booked_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handymanuser',
            name='handyman_services',
            field=models.CharField(choices=[('Painting', 'Painting'), ('Furniture Assembly', 'Furniture Assembly'), ('General Handyman', 'General Handyman'), ('Help Moving', 'Help Moving'), ('TV Mounting', 'TV Mounting'), ('Gardening and Removal', 'Gardening and Removing'), ('Disinfecting Services', 'Disinfecting Services'), ('IKEA Services', 'IKEA Services'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('All Services', 'All Services')], default='All Services', max_length=100),
        ),
        migrations.DeleteModel(
            name='servicemodel',
        ),
    ]
