# Generated by Django 4.2.30 on 2026-08-16 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userhandle', '0005_alter_handymanuser_handyman_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Painting', 'Painting'), ('Furniture Assembly', 'Furniture Assembly'), ('General Handyman', 'General Handyman'), ('Help Moving', 'Help Moving'), ('TV Mounting', 'TV Mounting'), ('Gardening and Removal', 'Gardening and Removing'), ('Disinfecting Services', 'Disinfecting Services'), ('IKEA Services', 'IKEA Services'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('All Services', 'All Services')], max_length=100)),
                ('price', models.PositiveIntegerField(verbose_name='Hourly rate')),
                ('description', models.CharField(blank=True, help_text="Optional — what this covers, e.g. 'flat-pack furniture, any brand'", max_length=300, null=True)),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Service offerings',
                'ordering': ('service',),
            },
        ),
        migrations.AddConstraint(
            model_name='serviceoffering',
            constraint=models.UniqueConstraint(fields=('handyman', 'service'), name='unique_service_per_handyman'),
        ),
    ]
