# Generated by Django 4.2.30 on 2026-08-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandle', '0006_serviceoffering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handymanuser',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='handymanuser',
            name='google_reviews_url',
            field=models.URLField(blank=True, help_text='Link to your Google Business profile or reviews page', max_length=500, null=True, verbose_name='Google reviews link'),
        ),
        migrations.AddField(
            model_name='handymanuser',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='handymanuser',
            name='website',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
